require 'simplecov'
require 'coveralls'

SimpleCov.formatter = Coveralls::SimpleCov::Formatter
SimpleCov.start do
   # This file was generated by https://github.com/ctran/annotate_models
   add_filter 'lib/tasks/auto_annotate_models.rake'
end
