require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe WorkshopsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Workshop. As you add validations to Workshop, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { FactoryGirl.build(:workshop).attributes }

  let(:invalid_attributes) { FactoryGirl.build(:workshop, max_participants: "twelve").attributes }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WorkshopsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all workshops as @workshops" do
      workshop = Workshop.create! valid_attributes
      get :index, session: valid_session
      expect(assigns(:workshops)).to eq([workshop])
    end
  end

  describe "GET #show" do
    it "assigns the requested workshop as @workshop" do
      workshop = Workshop.create! valid_attributes
      get :show, id: workshop.to_param, session: valid_session
      expect(assigns(:workshop)).to eq(workshop)
    end

    it "assigns the number of free places as @free_places" do
      workshop = Workshop.create! valid_attributes
      get :show, id: workshop.to_param, session: valid_session
      expect(assigns(:free_places)).to eq(workshop.compute_free_places)
    end
  end

  describe "GET #new" do
    it "assigns a new workshop as @workshop" do
      get :new, params: {}, session: valid_session
      expect(assigns(:workshop)).to be_a_new(Workshop)
    end
  end

  describe "GET #edit" do
    it "assigns the requested workshop as @workshop" do
      workshop = Workshop.create! valid_attributes
      get :edit, id: workshop.to_param, session: valid_session
      expect(assigns(:workshop)).to eq(workshop)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Workshop" do
        expect {
          post :create, workshop: valid_attributes, session: valid_session
        }.to change(Workshop, :count).by(1)
      end

      it "assigns a newly created workshop as @workshop" do
        post :create, workshop: valid_attributes, session: valid_session
        expect(assigns(:workshop)).to be_a(Workshop)
        expect(assigns(:workshop)).to be_persisted
      end

      it "redirects to the created workshop" do
        post :create, workshop: valid_attributes, session: valid_session
        expect(response).to redirect_to(Workshop.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved workshop as @workshop" do
        post :create, workshop: invalid_attributes, session: valid_session
        expect(assigns(:workshop)).to be_a_new(Workshop)
      end

      it "re-renders the 'new' template" do
        post :create, workshop: invalid_attributes, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        {
            name: "Awesome new name"
        }
      }

      it "updates the requested workshop" do
        workshop = Workshop.create! valid_attributes
        put :update, id: workshop.to_param, workshop: new_attributes, session: valid_session
        workshop.reload
        expect(workshop.name).to eq(new_attributes[:name])
      end

      it "assigns the requested workshop as @workshop" do
        workshop = Workshop.create! valid_attributes
        put :update, id: workshop.to_param, workshop: valid_attributes, session: valid_session
        expect(assigns(:workshop)).to eq(workshop)
      end

      it "redirects to the workshop" do
        workshop = Workshop.create! valid_attributes
        put :update, id: workshop.to_param, workshop: valid_attributes, session: valid_session
        expect(response).to redirect_to(workshop)
      end
    end

    context "with invalid params" do
      it "assigns the workshop as @workshop" do
        workshop = Workshop.create! valid_attributes
        put :update, id: workshop.to_param, workshop: invalid_attributes, session: valid_session
        expect(assigns(:workshop)).to eq(workshop)
      end

      it "re-renders the 'edit' template" do
        workshop = Workshop.create! valid_attributes
        put :update, id: workshop.to_param, workshop: invalid_attributes, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested workshop" do
      workshop = Workshop.create! valid_attributes
      expect {
        delete :destroy, id: workshop.to_param, session: valid_session
      }.to change(Workshop, :count).by(-1)
    end

    it "redirects to the workshops list" do
      workshop = Workshop.create! valid_attributes
      delete :destroy, id: workshop.to_param, session: valid_session
      expect(response).to redirect_to(workshops_url)
    end
  end

end
